ci:
  autoupdate_schedule: quarterly
repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt
        language: rust
        types: [rust]
        args: ["--all", "--"]
      - id: cargo-check
        name: cargo check
        entry: cargo check
        language: rust
        types: [rust]
        args: ["--workspace"]
        pass_filenames: false
      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy
        language: rust
        types: [rust]
        # https://doc.rust-lang.org/stable/clippy/
        args: [
          "--workspace",
          "--",
          "-Dwarnings",
          "-Dclippy::pedantic",
          "-Dclippy::nursery",
          "-Dclippy::cargo",
        ]
        pass_filenames: false
